workspace = { members = ["wasm/hello-wasi-cli"] }
[package]
name = "wasm-load-basecamp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
